### ISSUE TITLE
Cannot run on Ubuntu 18.04 LTS (WSL2)

### ISSUE THREAD

**Issue by haroldrandom** [microsoft/gnls#32]
it cannot run on Ubuntu 18.04 (WSL2) as always compiling about the missing of GLIBC_2.28
![image](https://user-images.githubusercontent.com/14357159/224676937-c8ee6de4-4782-484a-9b75-17e8d9a241e7.png)

Here is my ldd output
```Shell
> ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

And my libc did not have the 2.28 support.
![image](https://user-images.githubusercontent.com/14357159/224677438-0ec595c0-26af-4646-9dca-ad9a94cad3b0.png)

![image](https://user-images.githubusercontent.com/14357159/224677975-9426bfd3-5a95-471a-9694-f8e19952132a.png)

But it's a builtin glibc in Ubuntu 18.04 which means upgrading glibc is a very dangerous operation....

Does this GN language server support GLIBC_2.28 below?

**Comment by Qusic** [comment]
supporting this is quite tedious especially when ubuntu 18.04 (glibc 2.27) github runner has been [deprecated](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/).
before you can upgrade to newer OS versions, please use this fork:
https://github.com/MarshallOfSound/gnls
https://marketplace.visualstudio.com/items?itemName=MarshallOfSound.gnls-electron

closing as I will not work on supporting this scenario.
