### ISSUE TITLE
Crashes on M1 MacBook Pro

### ISSUE THREAD

**Issue by izackp** [microsoft/gnls#4]
Logs attached. 
[logs.txt](https://github.com/microsoft/gnls/files/7095682/logs.txt)

The primary issues seems to be:
`Error: dlopen(/Users/isaacpaul/.vscode/extensions/msedge-dev.gnls-0.1.0/build/darwin.node, 1): no suitable image found.  Did find:
	/Users/isaacpaul/.vscode/extensions/msedge-dev.gnls-0.1.0/build/darwin.node: mach-o, but wrong architecture
	/Users/isaacpaul/.vscode/extensions/msedge-dev.gnls-0.1.0/build/darwin.node: mach-o, but wrong architecture`

I'm assuming the plugin wasn't built for arm64 as that seems to be a common problem

**Comment by Qusic** [comment]
The native addon links against a GN static library, which is built with GN's own [script](https://gn.googlesource.com/gn/+/refs/heads/main/build/gen.py). It seems (correct me if wrong) not supporting cross compilation yet (GitHub actions run on x86 machines).

We may need to somehow refactor the build process (ideally build the entire addon with GN+ninja?) to fix this. Or in long term, we are also considering switching from GN's C++ parser to a tree-sitter one to avoid such issue altogether.

**Comment by Qusic** [comment]
It turns out to be [easier](https://gn.googlesource.com/gn/+/refs/heads/main/build/gen.py#329) than I think for a quick mitigation.
@izackp Can you help try if this [build](https://github.com/microsoft/gnls/actions/runs/1217676757) (download the `packages` artifact) works for you? I don't have access to an M1 mac machine for now.

**Comment by izackp** [comment]
@Qusic just tested a simple case. It seems to work. I'm getting syntax errors and all that jazz 👍
